# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

#use_frameworks!

target 'tempo-levelplay-mediation-adapter' do
  pod 'tempo-ios-levelplay-mediation', :path => '../'
end
